# agent/document_generator.py
# FRAMEWORM-AGENT for legal document generation
# Generates: demand letters, court complaints, rights notices, appeals
# All documents cite real statutes from the knowledge retriever
# Outputs in user's language after generation

from dataclasses import dataclass
from datetime import datetime, timezone
from intake.base import CaseType, LegalCase, LegalDocument, RecommendedAction, UrgencyLevel


# ── Document templates by case type ───────────────────────────────────────────

DEMAND_LETTER_TEMPLATES = {
    CaseType.HOUSING: """
{date}

To: {respondent_placeholder}
From: {user_placeholder}
Re: FORMAL DEMAND — Unlawful Eviction / Tenancy Rights Violation

Dear Sir/Madam,

I am writing to formally notify you that your actions regarding the above matter constitute a violation of my legal rights under {primary_statute}.

STATEMENT OF FACTS:
{key_facts_formatted}

LEGAL BASIS:
Under {primary_statute}, {legal_right_plain_english}

Furthermore, {secondary_statute} provides that {secondary_right}.

DEMAND:
I hereby demand that you:
1. Immediately cease and desist from the unlawful actions described above
2. Restore my rights as guaranteed under applicable law within 48 hours of receipt of this letter
3. Provide written confirmation of your compliance

NOTICE OF LEGAL ACTION:
If you fail to comply with this demand within 48 hours, I will have no alternative but to:
- File a formal complaint with the relevant housing authority
- Initiate legal proceedings before the competent court
- Seek all available remedies including damages and injunctive relief

This letter is written without prejudice to any and all legal rights I may have.

Yours faithfully,
{user_placeholder}
Date: {date}

IMPORTANT: Keep a copy of this letter and any response received. Send via registered post or email with read receipt.
""",

    CaseType.LABOR: """
{date}

To: {respondent_placeholder}
From: {user_placeholder}
Re: FORMAL DEMAND — Unlawful Employment Practices

Dear Sir/Madam,

I am writing to formally demand that you remedy the following violations of my legal employment rights.

VIOLATIONS IDENTIFIED:
{key_facts_formatted}

APPLICABLE LAW:
{primary_statute} provides that {legal_right_plain_english}

Your actions/inactions as described above constitute a direct violation of these statutory obligations.

IMMEDIATE DEMANDS:
1. {specific_demand_1}
2. Provide written acknowledgment of receipt of this letter within 24 hours
3. Remedy the above violations within 7 calendar days

ESCALATION NOTICE:
Failure to comply will result in immediate filing of complaints with:
- The Labour Department / Industrial Relations authority
- The relevant court of competent jurisdiction
- Any applicable regulatory body

I reserve all rights under applicable law.

Sincerely,
{user_placeholder}
Date: {date}
""",

    CaseType.CRIMINAL: """
{date}

NOTICE OF RIGHTS

To Whom It May Concern:

This notice formally asserts the constitutional and legal rights of {user_placeholder} in connection with the matter described herein.

RIGHTS ASSERTED:
Under {primary_statute}, {user_placeholder} is entitled to:
1. The right to be informed of all charges in clear language
2. The right to legal representation
3. The right to remain silent without adverse inference
4. The right to a fair and public hearing before an impartial tribunal
5. Protection against self-incrimination

CIRCUMSTANCES:
{key_facts_formatted}

Any actions taken in violation of the above rights will be documented and raised before the competent judicial authority.

This notice is served without prejudice.

{user_placeholder}
Date: {date}
""",
}

RIGHTS_NOTICE_TEMPLATE = """
YOUR LEGAL RIGHTS — {case_type_upper} CASE
Jurisdiction: {jurisdiction}
Generated by LEXSWARM Legal Defense System
Date: {date}

{rights_formatted}

IMMEDIATE ACTIONS REQUIRED:
{actions_formatted}

IMPORTANT WARNINGS:
- Do NOT sign any documents without reading them carefully
- Do NOT make statements to authorities without legal representation if possible  
- Keep copies of ALL correspondence
- Document everything with dates and times

Emergency legal assistance: Contact your nearest Legal Aid office
Free legal resources: https://www.lawhelp.org (US) | https://www.citizensadvice.org.uk (UK)
"""

COURT_COMPLAINT_TEMPLATE = """
IN THE COURT OF COMPETENT JURISDICTION
{jurisdiction}

{case_type_upper} COMPLAINT

Complainant: {user_placeholder}
Respondent: {respondent_placeholder}
Date Filed: {date}

1. JURISDICTION
This court has jurisdiction over this matter pursuant to applicable law.

2. PARTIES
The Complainant is an individual residing in {jurisdiction} who has suffered harm as described herein.

3. STATEMENT OF FACTS
{key_facts_formatted}

4. LEGAL VIOLATIONS
The Respondent's actions constitute violations of:
{statutes_formatted}

5. RELIEF REQUESTED
The Complainant respectfully requests this court to:
a) Issue an immediate injunction restraining the Respondent from continuing the unlawful conduct
b) Order the Respondent to restore the Complainant's rights
c) Award damages as appropriate under applicable law
d) Grant such other relief as this court deems just and proper

Respectfully submitted,
{user_placeholder}
Date: {date}

Note: This complaint was prepared with AI assistance. Review with a qualified lawyer before filing.
"""


class LegalDocumentGenerator:
    """
    FRAMEWORM-AGENT for legal document generation.

    Generates jurisdiction-aware legal documents with real statute citations.
    All documents include a note to review with a human lawyer before filing.
    """

    def __init__(self):
        self._llm = None   # optional LLM for enhanced generation

    def _format_key_facts(self, facts: list[str]) -> str:
        return "\n".join(f"- {fact}" for fact in facts[:5]) if facts else "- (facts to be detailed)"

    def _format_statutes(self, rights: list) -> str:
        return "\n".join(f"- {r.statute}: {r.plain_english}" for r in rights[:3]) if rights else "- Applicable statutes as determined by court"

    def _format_rights(self, rights: list) -> str:
        lines = []
        for i, r in enumerate(rights[:5], 1):
            lines.append(f"{i}. {r.right}")
            lines.append(f"   Law: {r.statute}")
            lines.append(f"   Meaning: {r.plain_english}")
            lines.append("")
        return "\n".join(lines)

    def _format_actions(self, actions: list) -> str:
        return "\n".join(f"{a.step_number}. {a.action} ({a.deadline})" for a in actions[:5]) if actions else "1. Seek immediate legal advice"

    def generate_demand_letter(self, case: LegalCase) -> LegalDocument:
        """Generate a demand letter appropriate for the case type."""
        template = DEMAND_LETTER_TEMPLATES.get(case.case_type,
                    DEMAND_LETTER_TEMPLATES.get(CaseType.HOUSING, ""))

        primary_right  = case.legal_rights[0] if case.legal_rights else None
        secondary_right = case.legal_rights[1] if len(case.legal_rights) > 1 else primary_right

        content = template.format(
            date=datetime.now(timezone.utc).strftime("%d %B %Y"),
            user_placeholder="[YOUR FULL NAME]",
            respondent_placeholder="[RESPONDENT NAME AND ADDRESS]",
            key_facts_formatted=self._format_key_facts(case.key_facts),
            primary_statute=primary_right.statute if primary_right else "[APPLICABLE STATUTE]",
            legal_right_plain_english=primary_right.plain_english if primary_right else "[YOUR LEGAL RIGHT]",
            secondary_statute=secondary_right.statute if secondary_right else "[SECONDARY STATUTE]",
            secondary_right=secondary_right.plain_english if secondary_right else "[ADDITIONAL RIGHT]",
            specific_demand_1=f"Immediately remedy the violation of {primary_right.statute if primary_right else 'applicable law'}",
        )

        return LegalDocument(
            doc_type="demand_letter",
            title=f"Demand Letter — {case.case_type.value.title()} Case",
            content=content.strip(),
            jurisdiction=case.jurisdiction,
            language=case.language,
            citations=[r.statute for r in case.legal_rights[:3]],
        )

    def generate_rights_notice(self, case: LegalCase) -> LegalDocument:
        """Generate a plain-language rights notice."""
        content = RIGHTS_NOTICE_TEMPLATE.format(
            case_type_upper=case.case_type.value.upper(),
            jurisdiction=case.jurisdiction,
            date=datetime.now(timezone.utc).strftime("%d %B %Y"),
            rights_formatted=self._format_rights(case.legal_rights),
            actions_formatted=self._format_actions(case.recommended_actions),
        )

        return LegalDocument(
            doc_type="rights_notice",
            title=f"Legal Rights Notice — {case.case_type.value.title()}",
            content=content.strip(),
            jurisdiction=case.jurisdiction,
            language=case.language,
            citations=[r.statute for r in case.legal_rights],
        )

    def generate_court_complaint(self, case: LegalCase) -> LegalDocument:
        """Generate a court complaint / application."""
        content = COURT_COMPLAINT_TEMPLATE.format(
            jurisdiction=case.jurisdiction,
            case_type_upper=case.case_type.value.upper(),
            date=datetime.now(timezone.utc).strftime("%d %B %Y"),
            user_placeholder="[YOUR FULL NAME]",
            respondent_placeholder="[RESPONDENT NAME]",
            key_facts_formatted=self._format_key_facts(case.key_facts),
            statutes_formatted=self._format_statutes(case.legal_rights),
        )

        return LegalDocument(
            doc_type="court_complaint",
            title=f"Court Complaint — {case.case_type.value.title()}",
            content=content.strip(),
            jurisdiction=case.jurisdiction,
            language=case.language,
            citations=[r.statute for r in case.legal_rights],
        )

    def build_action_plan(self, case: LegalCase) -> list[RecommendedAction]:
        """Build a step-by-step action plan based on case urgency."""
        actions = []
        step = 1

        if case.urgency == UrgencyLevel.CRITICAL:
            actions.append(RecommendedAction(
                step_number=step, action="Call emergency legal aid NOW",
                deadline="within 30 minutes",
                how_to="Search '[your city] emergency legal aid' or call national legal helpline",
                urgency=UrgencyLevel.CRITICAL, requires_human=True,
            ))
            step += 1

        actions.append(RecommendedAction(
            step_number=step, action="Document everything with timestamps",
            deadline="immediately",
            how_to="Take photos, screenshots, save all messages. Write down what happened with exact dates and times.",
            urgency=UrgencyLevel.HIGH, requires_human=False,
        ))
        step += 1

        actions.append(RecommendedAction(
            step_number=step, action="Send the generated demand letter",
            deadline="within 24 hours" if case.urgency.value >= UrgencyLevel.HIGH.value else "within 3 days",
            how_to="Send by registered post AND email. Keep proof of delivery. Fill in the [BRACKETED] fields first.",
            urgency=case.urgency, requires_human=False,
        ))
        step += 1

        actions.append(RecommendedAction(
            step_number=step, action="File complaint with relevant authority",
            deadline="within 48 hours if no response to demand letter",
            how_to=f"For {case.case_type.value} cases in {case.country}: contact the relevant government department",
            urgency=UrgencyLevel.MEDIUM, requires_human=False,
        ))
        step += 1

        if case.urgency.value >= UrgencyLevel.HIGH.value:
            actions.append(RecommendedAction(
                step_number=step, action="Consult a human lawyer",
                deadline="within 24 hours",
                how_to="Contact legal aid society, law school clinic, or bar association referral service",
                urgency=UrgencyLevel.HIGH, requires_human=True,
            ))

        return actions

    def generate_all_documents(self, case: LegalCase) -> list[LegalDocument]:
        """Generate all relevant documents for a case."""
        docs = []
        docs.append(self.generate_rights_notice(case))
        docs.append(self.generate_demand_letter(case))
        if case.urgency.value >= UrgencyLevel.HIGH.value:
            docs.append(self.generate_court_complaint(case))
        return docs
